### ISSUE TITLE
DQ Check - Admin page - have to save for each tab when defining rules

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1365] opened 2017-05-25 21:30 UTC
instance: dev1
SHA:

Right now, you have to click Save Changes separately for the Property and Tax Lot tabs when defining rules. Seems like it might be nice to just have to do save once.

But very low priority

**Comment by nllong** [comment] 2019-09-19 22:12
duplicate of #1848

**Closed by nllong** 2019-09-19 22:12 UTC
Labels: 2 Points, 2017, Data Quality Checking, Duplicate, Impact-3, P-3
