### ISSUE TITLE
BETTER - individual analyses for portfolios

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3968] opened 2023-04-04 16:49 UTC
When viewing a Portfolio Analysis Standalone HTML file there are links to download the individual building analyses. However, the download button does not display within the SEED `<iframe>`. See the below correspondance from Han Li at LBNL

>Hey [@Ross Perry](https://devetry.slack.com/team/U01S1Q61P5H), 
[@Daniel McQuillen](https://devetry.slack.com/team/U01MEGP2V35) and I have discussed the issue. The problem with the download links in the standalone portfolio analytics HTML is that they direct to BETTER web app (non API), which requires login. But our understanding is that individual SEED users don't have access to the master BETTER account. So our suggestion is that we disable the download links from the standalone portfolio HTML. You can add the download links somewhere outside of the iframe window via the standalone building analytics API

We will need to refactor the BETTER portfolio analysis flow to request individual PortfolioBuildingAnalyses for each building in the portfolio and attach them to the displayed analysis. I'm not sure where we should display the portfolio analysis.

Reference Documents 
[BETTER V2 Documentation](https://better.lbl.gov/docs/api/)
[Notebook created by better with example calls](https://colab.research.google.com/drive/1_XbRFm-DPYeaEqFePF8JevB_zQL6OFjt)

**Comment by perryr16** [comment] 2023-04-04 17:04
Email me for a jupyter notebook used for testing the SEED BETTER flow

**Comment by RDmitchell** [comment] 2023-04-05 23:13
I talked to Daniel about how all this works and now that I understand that the iFrame world is actually looking at the BETTER website, I'm not sure we should be doing any of the reports using iFrame. 

What happens if someone on the BETTER side deletes the run / report? 

Seems like we should be storing the actual HTML file that was obtained from the BETTER run, and then displaying it as HTML in SEED, not getting it via the iFrame world. ???

**Comment by RDmitchell** [comment] 2023-04-05 23:15
It is similar to how we are getting Audit Template XML files, ie, we're not looking at the Audit Template website, we are downloading the XML file and storing it in SEED so that we have it archived forever. 

I think we need to think about the BETTER reports in the same way, ie, download the HTML file, store it in SEED, and then the user will always have it archived, even if it gets deleted from the BETTER website.

**Comment by RDmitchell** [comment] 2024-02-05 20:17
@kflemin -- it would be nice if we could squeeze this in to the Q2 bug fixes, because right now the BETTER reporting world is a bit broken because of this. I suspect we will have to work with the BETTER team to figure out what the issue is.

**Comment by RDmitchell** [comment] 2024-02-22 17:59
Instance: staging
SHA: 1dc901360
Org; ID = 410

This is what is currently happening. 

In the Analysis screen, when you click on the link for an individual building
![image](https://github.com/SEED-platform/seed/assets/6314950/b66f8ff2-4105-4cc0-ae0d-35f19153e3cd)

The program displays this error message
![image](https://github.com/SEED-platform/seed/assets/6314950/55f92045-dce7-4afc-855a-dbd6f5851724)

We need to work with the BETTER team to figure out a way for this to work without having the users log into their accounts. The BETTER users have already entered an API key, specific to their account, in SEED. Hopefully we can leverage that instead of an actual login. 

I will get in touch with the BETTER team and see if we can schedule a meeting at some point in the next few months to work on this, so that it is working by the ACEEE Summer Session, where the BETTER team will presenting a paper on the SEED/BETTER connection.

**Comment by perryr16** [comment] 2024-02-22 20:58
thanks for documenting @RDmitchell

**Comment by RDmitchell** [comment] 2024-02-23 00:31
@perryr16 / @kflemin -- I sent the BETTER team an email today about this issue, and asked them to find some time to work with us on this in the next few months. The ACEEE conference is in the beginning of August, so we have some time to address this.

**Comment by RDmitchell** [comment] 2024-08-09 20:38
@perryr16 / @kflemin -- testing this today (LBNL staging for the 3.0.0 release), I can either generate individual reports for each building or portfolio reports, based on whether I select the Portfolio Report option when setting up the runs. 

This doesn't seem ideal, but at least it is possible to get to one or the other, but you need to do 2 separate runs. 

I think I am going to close this issue, and write up the current behavior in a new issue, and then at some point (probably in FY 25) with the BETTER team about how to improve this, ie, generate both the individuals reports, as well as only ONE portfolio report, for a given analysis.

**Closed by RDmitchell** 2024-08-09 20:38 UTC
Labels: Bug, BETTER
