### ISSUE TITLE
Number of Buildings not reporting properly 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#914] opened 2016-04-19 00:21 UTC
On the building list, for some reason the number of building is not reporting properly. I will give an example once this issue is created.

**Comment by RDmitchell** [comment] 2016-04-19 00:31
Now I am having trouble recreating the issue. Now the program is reporting the correct number of buildings in both the left nav bar and the building list header, where before it was only reporting "1" building in the building list header, no matter what I did (Clear Filter, Show All)

**Comment by RDmitchell** [comment] 2016-04-19 00:53
Now, using user's real data, I see the same issue -- "1" building is reported in the Building list header but 1,166 records are actually there.
![image](https://cloud.githubusercontent.com/assets/6314950/14624275/1a15d1c4-058e-11e6-8cf3-089607e3df67.png)

**Comment by RDmitchell** [comment] 2016-04-19 01:09
I can reproduce this issue by importing 2 years of public disclosure data from the DC benchmarking website. Here is a screen shot -- I have uploaded 2012 and 2013 data, and even though there will be some matching, the Building list is only reporting 1 building in the header, when it should be reporting 1,1218.

![image](https://cloud.githubusercontent.com/assets/6314950/14624544/87d0e968-0590-11e6-8d64-43df0344e1df.png)

I can share those files if they are useful in debugging this issue. I didn't see the problem when I imported the first file -- the number of buildings was reported correctly. But when I imported the 2nd file, mapped and matched it, the program then reported only 1 building in the Building list header.

**Comment by danielmcquillen** [comment] 2016-04-19 05:08
Dang. I can't recreate this issue locally. Trouble is, we're using Angular 1.4.10 on develop right now (as well as Django 1.9 and some other changes), so it's going to be even harder to recreate.
@axelstudios I think this has to do with ng-pluralize's binding to scope.number_of_buildings. Do you have any thoughts on what might be going wrong? 
@RDmitchell should we postpone working on this issue until the latest on develop gets pushed to staging, as it might be resolved by the upgrades. Or is this version going out to users soon?

**Comment by RDmitchell** [comment] 2016-04-19 17:40
@danielmcquillen -- I don't quite understand your comment "until the latest on develop gets pushed to staging".... what is in develop that is not in staging (ie, seedtest) ?

**Comment by axelstudios** [comment] 2016-04-19 18:18
I'm not able to reproduce this on seedtest or locally (using Angular 1.4.10, Django 1.8.9).

But I also don't think it's ng-pluralize - `search.number_matching_search` is exactly what is was bound to before that change.  I have a feeling it's an issue with the data coming from the backend (search results).  To test this, try the following:

Sidebar: This should return the maximum number of buildings
https://seedtest.lbl.gov/app/get_total_number_of_buildings_for_user/

Page header (from search results): Try this url with no query and check that `number_matching_search` at the very end matches the value returned from the last URL
https://seedtest.lbl.gov/app/search_buildings/

If it didn't match, we know where to start looking.  If it *did* match, then we need to see the search query that was passed along with the original request from the screenshot.  If you open the Chrome developer tools, go to the network tab, and browse to https://seedtest.lbl.gov/app/#/buildings , you should be able to check that it only matched 1 building, and then see what query it used:

Network Tab:
![image](https://cloud.githubusercontent.com/assets/411466/14650303/73319c6c-0628-11e6-8f49-bf904ec37e16.png)

Query Passed:
![image](https://cloud.githubusercontent.com/assets/411466/14650371/c5a8e5a4-0628-11e6-9e9a-4c4251b39356.png)

**Comment by RDmitchell** [comment] 2016-04-19 18:30
It's interesting that it seems no one can reproduce it on their local dev environment, because I can definitely see it on some of my seed accounts, but it does seem to be intermittent. 

I would like someone to figure it out -- @axelstudios or @danielmcquillen -- can you decide who will work on it?

And then I can add that person to the seedtest org where I see the problem, and we can figure out where to go from there. 

This has a pretty high priority because it is something that used to work that now doesn't seem to.

**Comment by danielmcquillen** [comment] 2016-04-20 00:23
On seedtest, confirmed that building_factory.search_buildings is getting back the correct number of buildings in the response...

![image](https://cloud.githubusercontent.com/assets/119496/14659743/d79e50be-06e1-11e6-8c74-d2db739ca60f.png)

So now trying to figure out why FE isn't populating this value to display...

**Comment by danielmcquillen** [comment] 2016-04-20 00:43
I think part of the problem is that when you navigate to the Building List view, the router calls building_factory.search_buildings, which returns the correct data. But when the view is instantiated, it's looking at the injected search_service for data like number_matching_search, and search_service has just default values, including 0 for number_matching search. 

I'm not sure why this issue doesn't manifest itself all the time...

**Comment by RDmitchell** [comment] 2016-04-20 01:20
Did we change something recently that would have changed this? I have never seen this problem before.

**Comment by danielmcquillen** [comment] 2016-04-20 01:28
Ok, I'm starting to think this is definitely a binding issue with ng-pluralize
I was able to recreate issue locally and validate that $scope.search.number_matching_search is indeed updated (line 485 in building_list_controller). So looks like the ng-pluralize directive isn't seeing that change.

**Comment by danielmcquillen** [comment] 2016-04-20 01:29
I placed the old way of doing this next to ng-pluralize. You can see it's binding ok to the value...

![image](https://cloud.githubusercontent.com/assets/119496/14660730/1b149f16-06eb-11e6-9344-b20887b7ab53.png)

**Comment by danielmcquillen** [comment] 2016-04-20 01:30
I'm out of time at the moment, so I can pick up again tomorrow. Next step is to either work on figuring out why ng-pluralize isn't binding right or just use our own simple function to set the bound prop.

**Comment by RDmitchell** [comment] 2016-04-20 01:36
Thanks for working on this Daniel !!!

**Comment by RDmitchell** [comment] 2016-04-20 01:37
I guess one question is whether there are other parts of the program that we should be testing that might also have been affected by this change.

**Comment by danielmcquillen** [comment] 2016-04-20 01:46
Looks like ng-pluralize was added to buildings.html, dataset_list.html, project_detail.html, and projects.html...I don't know if they'll all suffer the same issue though. @axelstudios what do you think?

**Comment by danielmcquillen** [comment] 2016-04-20 22:15
Ok, turns out the " | count: 0" code within ng-pluralize was causing the issue. Changing this:

`<ng-pluralize count="search.number_matching_search | number:0"`

to this...

`<ng-pluralize count="search.number_matching_search"`

fixed the issue. So *not* a binding issue but rather ng-pluralize didn't like how that pipe transformed the value of $scope.search.number_matching_search.

**Comment by danielmcquillen** [comment] 2016-04-20 22:25
I've opened a PR with an initial fix: https://github.com/SEED-platform/seed/pull/919
I'm going to check the other instances of ng-pluralize to see if they need similar modification.

**Comment by RDmitchell** [comment] 2016-04-20 23:27
Great, thanks Daniel !!

**Comment by danielmcquillen** [comment] 2016-04-20 23:33
There are example of embedding the number in ng-pluralize directly (e.g. http://stackoverflow.com/questions/14002870/how-to-format-a-number-in-ngpluralize) but I couldn't get that to work with search.number_matching_search, perhaps because of the scope.object.property nature of the value. In the interest of time, I'm just taking out the number and listing it separately.

**Comment by axelstudios** [comment] 2016-04-21 15:40
@danielmcquillen good catch!  I was totally expecting an issue from the backend.  I don't think we needed the number filter anyway, everything that I saw was already stored in javascript as integers.

**Closed** 2016-05-26 00:07 UTC
Labels: 1, Building List, Ready for Production
