### ISSUE TITLE
`seed.tests.functional.test_firefox` is breaking in Travis.

### ISSUE THREAD

**Issue by pipermerriam** [SEED-platform/seed#531] opened 2015-12-10 17:28 UTC
This test is breaking in CI.

**Comment by pipermerriam** [comment] 2015-12-10 22:57
@rHorsey @dangunter @RDmitchell 

Here's what I've tried in hopes that it inspires someone to have a clever idea.

* I've tried to reproduce the error locally (fresh installs of python requirements, js requirements in the same manner as they are installed on travis)
* removal of all of the caching for the travis-ci runs.
* extending wait time for the `wait_for_visibility` call in the test case just in case it's just taking longer on travis.
* dumping the HTML of the page at the point that the `test_firefox.py` fails which can be found here.  Couldn't see anything out of place.  https://gist.github.com/pipermerriam/17fc41694dcd8bd0c13a
* pouring over the code diff in #532 to see if **anything** jumps out at me.
* Looked over the historical test failures for the branch to try and figure out when the failure was introduced.  Couldn't identify a spot as it was covered up by other failures for most of the branch's history.

The behavior that I'm seeing is that it always fails on the check for the `verify-mapping-table` element's visibility on travis.  It passes just fine locally.  I'm royally stuck and out of ideas (for now).  Might be time for someone else to bang there head against this one for a bit as I think I'm hitting diminishing returns on my efforts.

I will probably try some version of the following when I get into the office tomorrow.

* Roll back all of the commits.
* Try to incrementally re-commit changes in smaller contained pieces (this might be REALLY hard given the intertwined nature of some of these things)
* Check if the test is failing at each step.

I'm a little burned on this and my brain feels mushy so I'm setting this down till the morning.

**Comment by RDmitchell** [comment] 2015-12-10 23:36
Changed Dan Gunter to Daniel McQuillen in the previous comment. 

I am wondering if @rHorsey should maybe take a look at this tomorrow?

**Comment by rHorsey** [comment] 2015-12-11 02:40
I'm booked tomorrow, but the unfortunate reality is that I've tried all the same steps as Piper over the last three days saving the historical test failures and dumping the html from travis. My next planned action was dumping the html, (thanks for doing this @pipermerriam!) and it shows exactly what I was afraid of - the 'verify-mapping-table' id is there, and not recognized. The critical method in all of this is [`wait_for_visibility`](https://github.com/SEED-platform/seed/blob/develop/seed/tests/functional/test_firefox.py#L278-L303), which I guess would be my next point of inquest. As Piper pointed out, rolling back the commits is going to be a huge amount of blood sweat & tears when we can see the id plain as day. I guess the only two remaining thoughts I have are to 1) try and render the linked html doc locally, and see if anything weird happens. I'm not sure how one would do this, or if it's even realistically possible. 2) Diff the above html doc against what is generated locally. Since I know virtually nothing about html or FE things in general (save configuring google chrome-beta on my personal linux box to work with netflix) I'd ask someone else to do both of these as I don't have the first idea what to look for or even if 1 is possible. Apart from that my next step would be to quiz Nick about how the travis environment is configured and make local reproduction my primary goal. This is a long-shot. I'm going to a funeral late next week, so my availability is pretty limited, but I could probably find a handful of hours early next week to look into this.

**Comment by RDmitchell** [comment] 2015-12-11 04:19
@pipermerriam & @rHorsey 
Seems like maybe we need to put this one on hold for a bit, and get @nllong to help look at it next week, particularly as I think that it isn't holding up any code that needs to be merged into develop and tested on seedtest. 
@pipermerriam -- it would probably be better for you to work tomorrow with @StephenCzarnecki on PR #523, as he's trying to put together some tests to see if that is the right approach

**Comment by pipermerriam** [comment] 2015-12-11 16:56
@RDmitchell got it.  I'm going to leave this issue alone and move onto #523

**Comment by RDmitchell** [comment] 2015-12-11 18:48
sorry to over-communicate ! Just wanted to move on to other issues. Thanks !!

**Comment by pipermerriam** [comment] 2015-12-11 18:54
Better to over-do it than under.

![awesome](https://cloud.githubusercontent.com/assets/824194/11752636/f25b2bd4-9ffd-11e5-8e19-cf1161131b39.jpg)

**Comment by nicholasserra** [comment] 2016-03-08 05:57
@RDmitchell this can probably be closed as i'm redoing this selenium setup.

**Comment by RDmitchell** [comment] 2016-03-08 06:17
OK, go ahead and close it.

On Mon, Mar 7, 2016 at 9:57 PM, Nicholas Serra <notifications@github.com>
wrote:

> @RDmitchell <https://github.com/RDmitchell> this can probably be closed
> as i'm redoing this selenium setup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/531#issuecomment-193619927>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Closed** 2016-03-08 16:55 UTC
