### ISSUE TITLE
Address sort -- alpha sort on street number (?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#271] opened 2015-06-16 23:57 UTC
in the Building List, when you do an ascending sort on Address Line 1, which is a field that is in the BuildingSnapshot database table, and is also a magic "matching" field, the sort is weird relative to how the program sorts by the street number. It appears to be doing an alpha sort (?) on a field that generally will start with a number.

Here is an example from a dummy Excel file. When I sort in Excel on the Address field, in ascending order, the program does the proper numeric and then alphabetic sort

Original order in Excel -- this is the order the file is in upon import into SEED

![image](https://cloud.githubusercontent.com/assets/6314950/8197030/e719f53a-1447-11e5-834b-567fe0146b03.png)

Sorting the Address field in Excel in ascending order

![image](https://cloud.githubusercontent.com/assets/6314950/8196976/0cb8904a-1447-11e5-8c28-1fabff8cb760.png)

And here is how SEED sorts the addresses
![image](https://cloud.githubusercontent.com/assets/6314950/8197119/cc025c3c-1448-11e5-9bc0-e5f47ac94827.png)

**Comment by RDmitchell** [comment] 2015-06-17 00:01
See sample file in 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LRlZWWnVuTkJhTjg&usp=sharing

**Comment by nicholasserra** [comment] 2015-09-11 20:30
I can't seem to reproduce this. I'm getting your desired sort order when I use the provided data file.

![screen shot 2015-09-11 at 4 29 35 pm](https://cloud.githubusercontent.com/assets/512288/9825605/643c5f3c-58a2-11e5-8ea1-97af0802f76a.png)

**Comment by RDmitchell** [comment] 2015-09-11 20:45
Interesting. Let me retest.

**Comment by RDmitchell** [comment] 2015-09-11 21:29
Claudine -- can you test this? On both seedtest and seed. thx

**Comment by cycustodio** [comment] 2015-09-14 17:44
I'm getting the same result as Robin, both in seed and seed test. The sorting is not done in the frontend, the HTTP request has the "sort" input. 

seed | seedtest
-----|-----
![seed_database_sort](https://cloud.githubusercontent.com/assets/8461331/9856975/cbe41702-5acc-11e5-9be9-ca1d4063938f.png) | ![seedtest_database_sort](https://cloud.githubusercontent.com/assets/8461331/9856979/cc0827a0-5acc-11e5-8a05-3dcd43cdcfe2.png)

-----
Out of curiosity, I tried sorting by a JSON field, Building Address. I'm getting the same result as Nick. Not sure why in his example, he has the database field with the correct sorting order. 

seed | seedtest
-----|-----
![seed_json_sort](https://cloud.githubusercontent.com/assets/8461331/9856978/cbfec02a-5acc-11e5-97f5-4d7da42d5380.png) | ![seedtest_json_sort](https://cloud.githubusercontent.com/assets/8461331/9856977/cbfe23e0-5acc-11e5-8240-49faa494c4bf.png)

**Comment by nicholasserra** [comment] 2015-09-14 17:46
Maybe it's how I mapped it. Can you give me exact steps to reproduce, with mappings, which resulted in the incorrect state? Thanks!

**Comment by cycustodio** [comment] 2015-09-14 18:07
1. Upload the sample file that Robin has, as a spreadsheet or Portfolio Manager file. 
2. In the mapping page, change "Building Address" to "Address Line 1". Didn't change any of the other mappings. 
![mapping_seedtest](https://cloud.githubusercontent.com/assets/8461331/9857686/d1048b14-5ad0-11e5-94ba-a524a69b0192.png)

3. Save mappings and start matching. 
4. Sort the data by "Address Line 1" in the Building List page.

**Comment by nicholasserra** [comment] 2015-09-16 21:54
So I tried it with both the database field and as a json data field. Both sorts were correct for me. I also tried to upload it as PM data, but the search page gave me 500 errors back, so it probably couldn't parse it.

I'm leaning towards this being a Postgres version issue. I think it was said that the dev server is running 9.2. I'm running 9.4 locally. Just a guess, but that may be the reason.

**Comment by RDmitchell** [comment] 2015-09-16 22:32
can you test on seedtest.lbl.gov and seed.lbl.gov and confirm that you see the behavior there?

**Comment by nicholasserra** [comment] 2015-09-17 18:05
Confirmed I see the incorrect sort on staging. I don't think I have access to production.

**Comment by RDmitchell** [comment] 2015-09-24 18:17
I am setting the milestone for this to Oct-Nov, when we are hopefully going to do some refactoring and can move to the latest version of Postgres

**Comment by RDmitchell** [comment] 2015-12-18 03:32
I believe this is still an issue. Am setting the milestone to January and assigning to @bravacheLBL to test to verify that it is still doing an alpha sort on the numbers in the address.

**Comment by bravacheLBL** [comment] 2016-01-29 23:53
Address line 1 is still sorted with alpha sort: 134 W Lincoln St before 1 E Washington Ave when in ascending order, both in seedtest and main seed.

**Comment by axelstudios** [comment] 2017-01-25 21:58
@RDmitchell I think we can close this one now that we have natural sorting

**Closed** 2017-06-07 16:28 UTC
Labels: Building List, Database
