### ISSUE TITLE
Put units on the field names everywhere

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2417] opened 2020-10-03 01:16 UTC
### Expected Behavior
I would like to see the units on the field headers, such as in Inventory List View, Inventory Detail View, mapping review, etc. 
### Actual Behavior
No headers

I just spent about a half hour trying to figure out why San Jose's Site EUI value wasn't the same as the value in the original ESPM spreadsheet. It finally occurred to me to look at the units settings for the org, and they were set to kWh/m2/year, rather than kBtu/sf/year. But I couldn't tell that from looking at the data in the Inventory List or Detail view. Also couldn't see it in the mapping or mapping review screens (after the fact).

We really need to display the units for the fields -- add the units to the column headers, etc. 

### Steps to Reproduce
change the units for site eui and the value changes
![image](https://user-images.githubusercontent.com/6314950/94979969-e23d9380-04da-11eb-8013-429a2ce2b718.png)
![image](https://user-images.githubusercontent.com/6314950/94980005-0e591480-04db-11eb-8d24-a9548a9b0958.png)

### Instance Information
Instance: seedv2
SHA: 2e7a2a0d

**Comment by adrian-lara** [comment] 2020-10-05 15:47
This is a duplicate of https://github.com/SEED-platform/seed/issues/2327 which has some important technical details for whoever picks this up.

@RDmitchell it could be worthwhile copying over this description and screenshots as a comment on that other ticket.

**Closed by adrian-lara** 2020-10-05 15:47 UTC
Labels: P-1

**Comment by RDmitchell** [comment] 2020-10-05 17:50
@adrian-lara -- I will add my screenshots etc to the original ticket. I don't know whether it should be escalated, but it seems like it should be included in the next round of development.
