### ISSUE TITLE
Bugs related to recently implemented caching utilities

### ISSUE THREAD

**Issue by pipermerriam** [SEED-platform/seed#527] opened 2015-12-09 17:06 UTC
cc @RDmitchell @rHorsey @danielmcquillen 

In our recent work on the new Labeling functionality in issue #494 daniel and I have uncovered some very strange bugs that seem related to the work that @rHorsey did back in November via PR #485, and more specifically in commit a9b4ca4aa57b81b032408983d4b7e16643cbb19a

One way this bug is manifesting is when you use the "Add to an existing project" functionality in the "Building Actions" menu while browsing the building list.  The `POST` to `/app/projects/add_buildings_to_project/` succeeds, but the next `/app/projects/get_adding_buildings_to_project_status_percentage/` raises a 500.

The source of this 500 error is from [`seed.utils.cache.get_cache#line-47`](https://github.com/SEED-platform/seed/blob/develop/seed/utils/cache.py#L47) where `data['status']` is accessed which throws a `KeyError` due to the key `'status'` not being present.

Looking at the api endpoint which initiates this task [`seed.views.projects.add_buildings_to_project`](https://github.com/SEED-platform/seed/blob/develop/seed/views/projects.py#L278) I see no place where the cache is populated with the appropriate cache key.  Looking at [`seed.tasks.add_buildings`](https://github.com/SEED-platform/seed/blob/develop/seed/tasks.py#L165) it appears that this cache key is first initialized on line 165 and it does not set a `'status'` key in the object that is written to the cache.

The bug we are seeing is caused by a race condition.  In the event that the request to `/app/projects/get_adding_buildings_to_project_status_percentage/` occurs before the `add_buildings` task has populated the cache, then the call succeeds because the `get_cache` function falls back onto the `default` value which contains a `'status'` key.  However, in the event that the task has already inserted a value into the cache, the call results in a 500 error.

This bug would not manifest itself in tests because tasks are run synchronously which guarantees that by the time the second call happens the entire process has run it's course.

**Comment by pipermerriam** [comment] 2015-12-09 17:24
I don't have any evidence to support this yet, but I suspect that the selenium/firefox errors we're seeing could be related to this as well.

**Comment by rHorsey** [comment] 2015-12-09 20:41
@pipermerriam @danielmcquillen At some level the issue is that when [attempting to access the progress of adding the buildings](https://github.com/SEED-platform/seed/blob/develop/seed/views/projects.py#L448) the get_cache command is used, while the setting of that [same progress key](https://github.com/SEED-platform/seed/blob/develop/seed/tasks.py#L165-L168) uses the set_cache_raw functionality, which does not guarantee that the required `cached_item['status']` key is created when first asked for. So depending on if the accessor looking for `'status'` or the writer looking to add in `'status'` completes their task first we can get the 500 return. The way we have been typically using get/set_cache can be seen [here](https://github.com/SEED-platform/seed/blob/develop/seed/tasks.py#L596-L602) and I think the section giving us race conditions could be configured the same way, e.g. rewriting [this](https://github.com/SEED-platform/seed/blob/develop/seed/tasks.py#L596-L602) as:
````py
data = {
       'percentage_done': 0,
       'numerator': 0,
       'denominator: 0,
       'status': 'queued'
}
set_cache( project.adding_buildings_status_percentage_cache_key, data['status'], data)
````
I tried to get all of the different cache's updated with the original pr to look like the above, but clearly I missed this one, and I suspect one other that I'm hunting down tomorrow. 

The other option I see is to instead alter the get_cache method to check for the existence of the `'status'` and if it doesn't exist setting it to `'undefined'` or something. I prefer the former as I think it makes the code cleaner, and response more standardized, but the later should probably be rewritten regardless to either check for the existence `'status'` and fail with a nice error message prior to assuming the key's existence. @axelstudios should be part of that discussion.

**Comment by RDmitchell** [comment] 2015-12-09 23:08
@rHorsey -- I talked to Daniel and in doing some testing, in the current set of code on seedtest, I can't make a new project. And if I had an existing project, which I don't in my current test case, I probably couldn't add new records to it. 

I am getting the following error
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
https://seedtest.lbl.gov/app/projects/get_adding_buildings_to_project_status_percentage/ 

So we need to get this fixed right away if we are going to make our December release schedule. 

![image](https://cloud.githubusercontent.com/assets/6314950/11701780/6b74a320-9e86-11e5-9cac-3ebfc2139dee.png)

**Comment by RDmitchell** [comment] 2015-12-09 23:11
@pipermerriam, @danielmcquillen -- we should probably get Ry's fix in for this problem before you all check in the label code, so that you can test his fix first. THX.

**Comment by pipermerriam** [comment] 2015-12-10 17:04
Also, I have some ideas on where to take this next.  I'm thinking that adding a layer on top of these cache functions that looks something like.

* `initialize_progress_key(key, initial_status="pending", **extra_data)`  - initializes the cache key for some progress meter.
* `update_progress_key(key, percentage_done, status="processing", **extra_data)` - updates the progress of the given key as well as the *status*.
* `finalize_progress_key(key, status="done", **extra_data)` - finalizes a progress key.  This method is potentially un-neccessary or can just be a convenience wrapper around `update_progress_key`.
* `get_progress_key_data(key)` - this shouldn't ever fail.  If any of the values are missing it should just fail gracefully.

Thoughts?

**Comment by RDmitchell** [comment] 2015-12-10 17:55
@danielmcquillen -- per @pipermerriam 's email, can you take the lead on merging Ry's PR #528 into your label develop branch?

**Comment by RDmitchell** [comment] 2015-12-10 17:56
@danielmcquillen -- seems that because of the time diff, @pipermerriam will take the lead on this. Once you are online for the day, check with Piper to see where things stand. THX !

**Comment by rHorsey** [comment] 2015-12-10 18:17
I think this looks pretty good. finalize_progress_key is most likely unnecessary, but it's a nice wrapper nonetheless. It will also fit well with all the 'finish_*' methods in the data-upload/mapping/matching world. That having been said, getting the caching stuff to work sync/async is painful.

**Comment by nllong** [comment] 2018-03-07 22:48
closing. Reopen if this appears again (2 years later :))

**Closed by nllong** 2018-03-07 22:48 UTC
