### ISSUE TITLE
Refresh Navigation results after mapping / matching

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#44] opened 2014-10-29 21:50 UTC
Refresh navigation results after mapping, matching, etc. to show updated number of buildings, etc.

**Comment by danielmcquillen** [comment] 2015-07-01 02:48
There's two ways I can see to do this, and they're philosophically different.

This is happening because the view isn't bound to a dynamic property indicating how many buildings are currently loaded for the user.

The first -- and easier -- way is to just set up a watch in menu_controller.js on the service function that loads the number of buildings:

```
 $scope.$watch(  function () { return building_services.total_number_of_buildings_for_user; }, 
                    function (data) {
                        $scope.buildings_count = data;
                    }, 
                    true);
```

The other option, a bit more involved but perhaps more "Angular" would be to bind the display in the view directly to a property on the "model." If we buy into the idea that we should bind whole objects with properties rather than just individual properties, we could do something like:

1. Add a *total_number_of_buildings_for_user* property to building_service.js so it can begin to act like a model

```var building_factory = { total_number_of_buildings_for_user: 0}; ```

2. Update this property in the appropriate methods in the service, for example, in the *get_total_number_of_buildings_for_user()* function
```javascript{8}
 building_factory.get_total_number_of_buildings_for_user = function() {
        // django uses request.user for user information
        var defer = $q.defer();
        $http({
            method: 'GET',
            'url': window.BE.urls.get_total_number_of_buildings_for_user_url
        }).success(function(data, status, headers, config) {
            building_factory.total_number_of_buildings_for_user = data.buildings_count;
            defer.resolve(data);
        }).error(function(data, status, headers, config) {
            defer.reject(data, status);
        });
        return defer.promise;
    };
```

3. In the *menu_controller*, rather than exposing a $scope.buildings_count property for the view to bind to, instead bind the whole model and let the view select which property it needs

```
 $scope.building_services = building_services;
```

**Comment by danielmcquillen** [comment] 2015-07-02 04:15
As I get more into this issue I think a topic for later refactoring is how can we establish a uniform way of exposing properties of models that extend across the application.

Right now the app is using an inconsistent mixture of events and methods in callbacks within controllers to try to figure out "how many of x for this user are there," be it projects, datasets, organizations or buildings.

This is why the menu wasn't working properly to automatically update the counts shown in the each nav item.

Ideally, there should be one model (DRY) per item type that any controller can look at to see how many e.g. buildings there are. Then we can bind different views directly to that property and know that we'll get the right value. Naturally these items should be the services for each type.

So recommendations for future refactoring would be:
* The model should contain properties about its state that all views can access. The controller will simple set up the binding.
* The model should update its properties automatically to reflect its state after operations that affect the state have successfully completed, rather than waiting for a controller to update those properties (e.g. update building count after a successful creation). Remove the inconsistent way each controller is asking the model to update its count.
* Get rid of events (e.g. 'datasets_updated'), callbacks used for updates, and watches where possible and just bind views to model properties directly (see above linked article)

**Comment by danielmcquillen** [comment] 2015-07-03 01:41
I've committed a fix for this in my own fork, 
https://github.com/danielmcquillen/seed/commit/e05d22e7631415113b39111a27dbac2c5c4b5deb

Still trying to figure out how to do create another pull request for this. Perhaps I can have only one pull request open at a time?

**Comment by danielmcquillen** [comment] 2015-07-05 23:19
This fix has been added to my pull request: https://github.com/SEED-platform/seed/pull/276

**Comment by cycustodio** [comment] 2015-07-27 20:18
Tested and confirmed working.

**Closed** 2015-08-10 18:25 UTC
Labels: 3, GUI
