### ISSUE TITLE
Error Report on Meter Data Upload

### ISSUE THREAD

**Issue by dreneden1** [SEED-platform/seed#3179] opened 2022-03-21 22:11 UTC
**Is your feature request related to a problem? Please describe.**
We are having lots of problems when we try to upload meter data using the "Upload Portfolio Manager Meter Usage" button. We are specifically trying to upload data from the "data request" format from ENERGY STAR Portfolio Manager. See attached file as an example. When we upload the "monthly usage" tab, we often get the error that the data isn't in the required format "An error occurred while processing the file. Please ensure that your file meets the required specifications.", but we don't have any details on what the required specifications are or where/how we didn't meet them. 
[Uploading Monthly Data.xlsx](https://github.com/SEED-platform/seed/files/8319486/Uploading.Monthly.Data.xlsx)

**Describe the solution you'd like**
ENERGY STAR Portfolio Manager has a similar feature where you can upload data via spreadsheet. When the file doesn't meet the required specs, you get an error report that specifies exactly why the file didn't upload. 

![image](https://user-images.githubusercontent.com/60278745/159371486-c737f19e-6c5e-4325-a7c8-8912f6c9f351.png)

**Describe alternatives you've considered**
The meter data upload works better when we use the "Download my portfolio" option from ESPM and then upload this file using the "Upload Portfolio Manager Meter Usage" button; however, we don't have all of the data in this format since participants don't "share their property" with us, they simply respond to the data request. 

**Additional context**

![image](https://user-images.githubusercontent.com/60278745/159371911-a5b4c5ed-cec1-42d5-805e-85943e46b13a.png)

**Comment by RDmitchell** [comment] 2022-07-23 21:27
This would be a very good enhancement to add.

**Comment by isalanglois** [comment] 2022-12-07 20:50
@RDmitchell Can we follow-up to see if this is still an issue? @haneslinger addressed some issues with this feature, and may be working now

**Comment by RDmitchell** [comment] 2022-12-07 21:03
@isalanglois -- I don't have a good ESPM data set that would allow me to test this. Maybe we should have Dan test on the staging server?

**Comment by RDmitchell** [comment] 2022-12-07 21:05
@isalanglois -- I can test uploading the file he references, I just don't have a dataset in ESPM that would show what he is showing at the beginning of the issue description. So I will start with that. 

But I can't do much testing until tomorrow afternoon.

**Comment by RDmitchell** [comment] 2022-12-07 21:14
I can import the file referenced at the beginning of this issue, as long as I switch the tabs so that the Information and Metrics tab is first, so that the program can create the property records with the PM Property ID, and the Monthly Usage (meter data) 2nd.
![image](https://user-images.githubusercontent.com/6314950/206297455-0c9a9196-b332-4b73-b7ef-eebebb371cdc.png)
![image](https://user-images.githubusercontent.com/6314950/206297686-dcdb18b7-d6fa-4715-a133-3edc8d1b562b.png)

**Comment by haneslinger** [comment] 2022-12-08 15:58
sweet, I think we are good to close then?

**Comment by RDmitchell** [comment] 2022-12-08 19:27
@nllong -- I guess we need to let @dreneden1 know when this is added to the release patch?

**Comment by dreneden1** [comment] 2022-12-08 19:59
@RDmitchell please do!

What was the solution in the end? Will there be a more detailed error message when the upload fails? 
I noticed in the screenshot above a "delete meters" feature - that's great! Is that for a different ticket?

**Comment by RDmitchell** [comment] 2022-12-08 21:25
@dreneden1 -- we have implemented delete meters, and will move it to the staging server soon. I will ping you when it's there so you can test. 

Not sure about the more detailed error message on failed upload. @nllong / @isalanglois -- we might need to add another issue for that feature.

**Comment by dreneden1** [comment] 2022-12-08 22:50
@RDmitchell I'm confused... This ticket was about adding an error report when files are uploaded and rejected. It seems like the solution was to implement the ability to delete meters (which is a great and much needed feature). How are those two related?

**Comment by RDmitchell** [comment] 2022-12-09 23:36
@haneslinger -- @dreneden1 is correct, I don't think we addressed his original issue, which is a way to see what the problem is with his file when he is uploading it from Portfolio Manager and gets the message "An error occurred while processing your file". 

In this particular case, with this particular file, the problem was that SEED couldn't interpret the data properly because the tab order was incorrect, and could be fixed by reversing the tab order. Which is what I did and then the file could be imported. 

But the bigger issue is to give users more information about what is wrong with the file so that they know how to fix it. 

@nllong -- We may have to think about this a bit because there are many different possible problems with files. Does SEED have enough information to give the user an accurate error message about what is wrong with the file?

**Comment by haneslinger** [comment] 2022-12-12 19:19
Hey @dreneden1,

I've just tried uploading the linked file and I didn't have any issues. Is this still plaguing you? If so, could we set up a time to go threw it together so I can look at your logs?

**Comment by dreneden1** [comment] 2022-12-14 17:49
Hi @haneslinger, can you try with this one? One of our clients is trying to upload it and there is no problem with the annual data, but when we come to add the meter data, we are getting that error message. 

[BBO Participants - 2019 - Ottawa Data Upload Issue.xlsx](https://github.com/SEED-platform/seed/files/10230400/BBO.Participants.-.2019.-.Ottawa.Data.Upload.Issue.xlsx)

**Comment by RDmitchell** [comment] 2022-12-14 17:57
@haneslinger -- on the LBNL production instance, which is SHA 09736c1d6, there are issues importing meter data. Not sure if these two things are related, but thought I would chime in.

See this issue: #3450

**Comment by haneslinger** [comment] 2022-12-14 21:37
Thank you both for the extra information! I have been able to recreate and error with [BBO Participants - 2019 - Ottawa Data Upload Issue.xlsx](https://github.com/SEED-platform/seed/files/10230400/BBO.Participants.-.2019.-.Ottawa.Data.Upload.Issue.xlsx) on develop and I am investigating.

**Comment by anchapin** [comment] 2022-12-16 18:54
@dreneden1 it's working now with the PR (#3716) that I just created.

**Closed** 2022-12-16 22:12 UTC
Labels: Feature, To Investigate, Meter Data, User Support

**Comment by dreneden1** [comment] 2023-01-05 23:55
@haneslinger thanks for prompting the fix, and @anchapin thanks for the fix!

@haneslinger circling back to the original topic of this issue, will there now be an error report when a file doesn't upload?

**Comment by RDmitchell** [comment] 2023-01-27 23:49
@dreneden1 -- We have added error messaging when importing meters. 

In the future, when you get errors it would probably be good to let us know (you could make a new issue as you did here) and we can look into whether we can make the error messages more helpful to the user.

**Comment by dreneden1** [comment] 2023-01-30 16:52
> 

Sounds good - thank you @RDmitchell !
