### ISSUE TITLE
Create the note event type functionality for Property Timeline

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3845] opened 2023-02-10 20:10 UTC
Related to #3769. Use the [bps-feature-develop](https://github.com/SEED-platform/seed/tree/bps-feature-develop) branch as the base. When Property Timeline page is loaded the associated events for that property in the database need to be loaded into the table for the note event type.

The meta data associated with a note event is the note name, note id, and note time stamp. FYI, only the manual notes should be included not the log notes (this should be handled via a different ticket already).

**Comment by haneslinger** [comment] 2023-03-20 18:33
@anchapin I think this can be put in review?

**Comment by RDmitchell** [comment] 2023-04-07 23:09
Instance: dev1
SHA: https://github.com/SEED-platform/seed/commit/c94869068feb021cbb258ac4815be65b98dbc5e0 (2.18.0)

I added a note from the detail view, but I didn't know what cycle I was entering it into -- we might want to show the current cycle on all the relevant pages? 

Turns out the program put the Note in the 2019 cycle, which was the cycle I had come from in the Property Detail page, but I didn't remember which one it was. 

I will make a separate issue for that possibility, and in the meantime, I will close this issue, because it seems to be working as designed

**Closed by RDmitchell** 2023-04-07 23:09 UTC
Labels: Feature, Assign, BPS
