### ISSUE TITLE
DQ results in mapping not consistent when importing a Portfolio Manager file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1505] opened 2017-11-13 23:59 UTC
This is somewhat related to #1488. 1488 was resolved for importing the file type "Spreadsheet" but still seems to remain when importing (the same file) setting file type to "Portfolio Manager".

See this folder with a sample file and doc 
https://drive.google.com/open?id=0B3fTKpZ9Dx7LcmRITE5ncW9CNGc

This probably also relates to the issue described in #1367

**Comment by adrian-lara** [comment] 2020-01-17 22:54
Was not able to reproduce this - must have been resolved in the last couple years.

**Closed by adrian-lara** 2020-01-17 22:54 UTC
Labels: 2 Points, 2019 Dec Release, Data Quality Checking, Impact-2, Not Reproducible, P-3
