### ISSUE TITLE
Can't log in to Portfolio Manager from SEED

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3322] opened 2022-06-21 22:59 UTC
**Describe the bug**

When trying to log into Portfolio Manager to automatically import data, the City of Berkeley is getting a 

**Expected Behavior**

Should be able to log in to a user's Portfolio Manager account, select a template and have the data from that report template automatically uploaded into SEED 

**Actual Behavior**

The program is giving a 500 error

See the video in the folder below, from the **beginning to 1:55** in, which shows the exact problem
G:\My Drive\SEED Shared Folder\Software Development\Issues\Issue 3322
SEED_Issue-3322.mp4

**Steps to Reproduce**

See the video referenced above.

**Instance Information**

Instance: production
SHA: 6ffea0837

**Additional Context**

@areagan-cob at the City of Berkeley reported this problem.

**Comment by nllong** [comment] 2022-08-24 15:46
@aviveiros11  -- can you verify if this is still an issue?

**Comment by aviveiros11** [comment] 2022-08-25 19:30
Hey @nllong or @RDmitchell could I get access to the SEED shared drive to take a look at that video.  Please use my viveiros.austin@gmail.com email.

**Comment by RDmitchell** [comment] 2022-08-25 19:39
@aviveiros11 -- I just shared the folder with you that has the video. Let me know if you have any issues accessing it.

**Comment by aviveiros11** [comment] 2022-08-29 17:24
I was unable to reproduce the behavior with PM however I did suspect that we weren't handling the case of an account without report templates but realized we actually DO handle that case as well [here](https://github.com/SEED-platform/seed/blob/3a18e847299e90f7c1169a248ceb97a86f8b67dc/seed/views/v3/portfolio_manager.py#L287)

![Image](https://user-images.githubusercontent.com/31779424/187259803-d2b9adac-9c0f-4fb9-ac90-0782bb353794.png)

**Comment by RDmitchell** [comment] 2022-08-29 18:02
seems like we should close this and we can always open another bug if needed.

**Comment by RDmitchell** [comment] 2022-08-29 18:03
@nllong -- maybe someone should get in touch with Ammon at the city of Berkeley to see if they are still having this problem, rather than closing without checking with them.

**Comment by aviveiros11** [comment] 2022-08-29 18:32
I'd be happy to reach out if you give me an up-to-date email 😄

**Comment by RDmitchell** [comment] 2022-08-29 23:24
@aviveiros11  / @areagan-cob (Ammon) -- maybe the two of you can connect and see if Berkeley is still having this problem)

**Comment by areagan-cob** [comment] 2022-08-30 20:45
@RDmitchell @aviveiros11 - Hi All - I just tried to log-in to our ESPM account and get the benchmarking reports but am still running into the same issue. I've triple checked and am using the right credentials. see the error that I keep getting below:

![image](https://user-images.githubusercontent.com/107960162/187539691-33ef1667-3d8d-48a2-ba3e-3be37c2d9d65.png)

**Comment by aviveiros11** [comment] 2022-08-30 20:53
Hey @areagan-cob - sorry to hear you are still having trouble.  Can you confirm your account has Report Templates to be selected?  I will continue to stomp on it a bit to see if I can reproduce it, however, if that doesn't work would you mind hopping on a quick 15-minute call so I can check a few things out?

**Comment by areagan-cob** [comment] 2022-08-30 20:59
Hi Austin - it has templates to pull from, I was using the "Get Reports" feature in May to pull the latest 2021 benchmark reports and then after using it a few times it stopped working. I'd be happy to jump on a quick call and walk you through the issue. Im free for the next hour (2-3pm PST) and throughout tomorrow if there are some times that work for you. - Ammon

**Comment by aviveiros11** [comment] 2022-08-30 21:04
Let's plan on tomorrow at 11:30 MST if that works for you.  Could I grab your email also to send an invite?

**Comment by areagan-cob** [comment] 2022-08-30 21:17
@aviveiros11 that time works for me, send the invite to areagan@cityofberkeley.info

**Comment by aviveiros11** [comment] 2022-08-31 18:01
After chatting with @areagan-cob we noticed that this is only occurring from one of two accounts that they use on ESPM.  Action items coming out of this meeting:

- Confirm report template nested case is handled 
- Re-create Berkley behavior by mimicking their report template structure
- Review any ESPM API changes that have been made recently? 
- possibly get access to Berkley ESPM account to further investigate.

**Comment by RDmitchell** [comment] 2022-08-31 18:37
@aviveiros11 -- thanks for working with @areagan-cob on this !!

**Comment by nllong** [comment] 2022-11-22 18:15
This might be related to #3593

**Comment by RDmitchell** [comment] 2022-11-22 18:41
@aviveiros11 -- did this get fixed?
@areagan-cob -- is this still an issue for you?

**Comment by RDmitchell** [comment] 2023-01-09 21:06
@areagan-cob -- Ammon, are you still having this issue?

**Comment by areagan-cob** [comment] 2023-01-09 21:12
@RDmitchell - Sorry for not checking this back in November! I just checked and I'm still getting the "Error: Internal server error" message.

**Comment by RDmitchell** [comment] 2023-01-09 21:15
@haneslinger / @nllong -- we need to work with @areagan-cob about this issue to figure out what is going on.

**Comment by haneslinger** [comment] 2023-01-09 22:50
I believe that was fixed [here](https://github.com/SEED-platform/seed/issues/3593)

**Comment by RDmitchell** [comment] 2023-01-10 00:44
@haneslinger / @nllong -- is this something that @areagan-cob could check on our staging server once it gets updated to the latest 2.17 release?

**Comment by RDmitchell** [comment] 2023-01-10 01:07
@haneslinger / @nllong / @isalanglois -- I am going to move this into the Q2 Project, under To Do, since we need to get this working for @areagan-cob, and we need to close out the Q1 project.

**Comment by haneslinger** [comment] 2023-01-12 23:43
It's hard to says what exactly caused this problem, but can you retest this? There have been relevant bug fixes since 5 months ago.

It's currently working with other logins, so if it's still broken for yours, we can set up sometime to debug :)

**Comment by RDmitchell** [comment] 2023-01-12 23:47
@areagan-cob -- we have put the latest release, 2.17.0, on the LBNL staging server (https://seeddemostaging.lbl.gov/) and your data has been copied over from the production server to the staging server. You should be able to log in as you would on the production server. Could you test logging in to your ESPM account from the staging server and see if you are still seeing this issue? Thanks !!

**Comment by areagan-cob** [comment] 2023-01-18 16:26
@haneslinger / @nllong / @RDmitchell -- Hi All, I just tested the issue on the staging server (2.17.0 release) and the problem is fixed. I can log-in/link to my ESOM account again. Thank you all for fixing this!

**Comment by haneslinger** [comment] 2023-01-18 17:57
Yay! Closing.

**Closed by haneslinger** 2023-01-18 17:57 UTC
Labels: Data Import
