### ISSUE TITLE
When Deleting record, need option to not delete associated records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1214] opened 2017-01-20 02:58 UTC
Right now when you delete a record in either the Tax Lot or Property View, the program deletes any associated records at the same time. 

Need to add the option (ie, probably ask the user or have a default setting that can be overridden) that the relationship is broken (ie, the records in the junction table are deleted) but the associated records are not deleted, ie, they are now orphaned, but at least they are still there, and can be matched against later.

**Comment by axelstudios** [comment] 2018-03-07 21:26
When you select property and/or taxlot rows in the list view and use the `Delete` action, only the selected rows are deleted and associated (unchecked) records remain.  Is there a different use case that this ticket refers to?

![image](https://user-images.githubusercontent.com/411466/37119009-4f639958-2213-11e8-998d-3539b4f23a53.png)

**Comment by RDmitchell** [comment] 2018-03-07 21:34
Hmm, this seems like different behavior from previous versions. 

In the past, if you deleted a property record, it would delete the associated tax lot records also. 

If it's true that the paired record is not deleted, which it seems to be, then this issue is no longer relevant

Why does the modal even say "0 tax lots" if it will never delete the paired tax lot records when you delete a property record? And vice versa, presumably, if you are deleting a tax lot record.

Shouldn't the message just say "Are you sure you want to delete 1 property?"

With possibly a note that never changes saying that any records paired to the deleted record will not be deleted but will become unpaired?

**Comment by nllong** [comment] 2019-09-19 22:17
@RDmitchell can you verify this item?

**Comment by RDmitchell** [comment] 2019-09-25 00:19
@nllong -- 

It seems that if you select one record at a time, in either the Property or Tax Lot list tabs, the program doesn't delete the associated record. 
![image](https://user-images.githubusercontent.com/6314950/65559310-12794c00-deef-11e9-972c-213defd7ee9b.png)

However, if you select all the records (including all the records resulting from filtering the records) in either tab, it appears that the program deletes all the records in that tab and all their associated records -- this is probably by design and I think is OK.

![image](https://user-images.githubusercontent.com/6314950/65559395-5ec48c00-deef-11e9-943a-8a5edd9e16c8.png)

**BUG** - should I make a new issue for this?

However, there appears to be a bug in that even after a Tax Lot has been deleted (it no longer exists and is not associated with a property), the program doesn't clean up the Associated Tax Lot field -- it still displays the value of the now non-existent Tax Lot

![image](https://user-images.githubusercontent.com/6314950/65558957-8c103a80-deed-11e9-9922-4b9e4424d4af.png)

In the Tax Lot table, I delete Tax Lot ID 01830857, but in the Property view, the program still displays that value in the Associated Tax Lot ID field, even though it does not display it in the Jurisdiction Tax Lot ID field (because the record no longer exists).
![image](https://user-images.githubusercontent.com/6314950/65559097-1a84bc00-deee-11e9-993d-e51646ff94d0.png)

Looking at the Tax Lot tab, there is only one record now in that table, and it is not 01830857
![image](https://user-images.githubusercontent.com/6314950/65559184-7d765300-deee-11e9-8628-f0b396d94c24.png)

**Comment by adrian-lara** [comment] 2019-10-29 04:12
Capturing some research notes for follow up discussions...

Deleting a paired Tax Lot does actually delete the record. The latest issue/case given above is happening because the Property value within "Associated Tax Lot ID" (DB-col: `lot_number`) isn't updated when the paired Tax Lot is deleted. 

Implementing a `pre_delete` hook can be used to fix this issue. I don't see any issue with this fix and it seems to work.  But my local testing around this fix led me to research this "Associated Tax Lot ID" field. 

@RDmitchell or @nllong 
What is its purpose? How is it used by users? How is it different from "Jurisdiction Tax Lot ID (Tax Lot)"?

**Comment by RDmitchell** [comment] 2019-10-30 21:18
@adrian-lara - at this point I am not sure why there is "Associated Tax Lot ID". I think it is extraneous, because when the files are mapped and paired properly, the "Jurisdiction Tax Lot ID" field can be displayed with the Property fields in the list view, and that seem to me to be the equivalent of "Associated Tax Lot ID". 

Can we just "get rid of it" somehow ? Not sure what that means ... but maybe it doesn't have to be part of the linking between Tax Lots and Property fields. ??

**Comment by adrian-lara** [comment] 2019-11-04 18:36
@RDmitchell - I chatted with Nick about this and there might be some historical reason why "Associated Tax Lot ID" exists and should continue to exist. 

More research is needed on our end, but if we end up keeping the field, I plan on implementing the fix I mentioned in my last message, so at the very least, it works as intended.

Just for our knowledge, do you have any insight on if and how users use this field?

**Comment by RDmitchell** [comment] 2019-11-12 18:54
@adrian-lara / @nllong -- I don't exactly remember the history of Associated Tax Lot ID, but I think it was something that Nathan Addy, the person who designed the db restructure a few years ago, thought was necessary. I actually don't think it is, but I guess we can leave it for now, although it seems like it is complicating your life in terms of this issue.

**Comment by nllong** [comment] 2019-11-12 19:50
The "associated tax lot id" is the PropertyState.lot_number field:
```
}, {
            # This field should never be mapped to!
            'column_name': 'lot_number',
            'table_name': 'PropertyState',
            'display_name': 'Associated Tax Lot ID',
            'data_type': 'string',
        }, {
```
The lot_number is used to store a string relationship (semicolon delimited) between properties and tax lots:

```
            if isinstance(merged_state, PropertyState):
                joined_lots = set()
                if state1.lot_number:
                    joined_lots = joined_lots.union(state1.lot_number.split(';'))
                if state2.lot_number:
                    joined_lots = joined_lots.union(state2.lot_number.split(';'))
                if joined_lots:
                    merged_state.lot_number = ';'.join(joined_lots)
```

and
```
    if 'PropertyState' in table_mappings:
        if delimited_fields and delimited_fields['jurisdiction_tax_lot_id']:
            table_mappings['PropertyState'][
                delimited_fields['jurisdiction_tax_lot_id']['from_field']] = ('PropertyState', 'lot_number', 'Lot Number', False)
```

so in short, we have to be careful removing this field. It is used in many places.

**Comment by RDmitchell** [comment] 2019-11-12 19:52
@nllong / @adrian-lara -- ok, that's fine. We can keep it.

**Comment by adrian-lara** [comment] 2019-11-12 21:36
This is on my plate, so I'll do more research/testing on what it'd take to remove it and offer a suggested path forward once I do that.

Thank you both for the background/info!

**Comment by adrian-lara** [comment] 2019-12-04 19:21
@RDmitchell @nllong 
As far as I can see, the most notable use of `lot_number` now is that it's an integral piece of automatically pairing records on import.  In order to remove this field, we'd need to revamp how pairings are automatically established during file import.

Revamping this automatic pairing is likely a task that would take 20+ dev hours along with extensive testing before allowing for the change to be deployed to users.

If making this change isn't desired right now, we could do one or both of the following (which is would take anywhere from 1 to 4 dev hours):
1. Hide the `lot_number` column (displayed as "Associated Tax Lot ID") from users. This would be done by a migration to update current column profile settings and removing it as an option on the column profile page.
2. Implement a `pre_delete` hook on TaxLotProperty to update this `lot_number` on the associated PropertyState. This should keep the lot_number value in sync with the "Jurisdiction Tax Lot ID (Property)" column.

**Comment by RDmitchell** [comment] 2019-12-04 20:31
@adrian-lara / @nllong 

I would say let's put this one in the ice box for now.

**Comment by adrian-lara** [comment] 2019-12-11 20:14
Closing this since this has diverged from what the issue was discovered to be. #2044 more succinctly describes the "actual" issue.

**Closed by adrian-lara** 2019-12-11 20:14 UTC
Labels: 2 Points, 2019 Dec Release, Enhancement, Impact-3, Inventory List, No Longer Valid, P-3
