### ISSUE TITLE
Admin: Create User: Prevent adding an org with existing name

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2098] opened 2020-01-30 20:05 UTC
### Expected Behavior
under "Create a User", if I create a user and enter a new Organization Name that already exists during that definition, I would expect that the program would tell me that the org already exists and that I need to make a new org name
### Actual Behavior
The program now allows an admin to create a new user and enter an org name that already exists under the "Or Create New" section of "Create a User".
### Steps to Reproduce
Under "Create a user", enter new info in User First Name, User Last Name and User E-Mail, and then under the "Or Create New" section, enter an existing Organization Name.
![image](https://user-images.githubusercontent.com/6314950/73485739-85407b00-4358-11ea-8151-c5ca216a4640.png)
SEED allows this new org with the same name as existing orgs to be defined
![image](https://user-images.githubusercontent.com/6314950/73485845-bcaf2780-4358-11ea-9a0d-3d4b787ca7fe.png)

### Instance Information
instance: LBNL staging
SHA: 395db33d (2.6.1)

**Comment by aviveiros11** [comment] 2020-04-14 17:34
Appears to be a duplicate of #1592 solved by @axelstudios

**Closed by aviveiros11** 2020-04-14 17:34 UTC
