### ISSUE TITLE
Deleting a rule after saving previous changes does not reactive save buttons

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2114] opened 2020-02-19 16:05 UTC
### Expected Behavior
Any changes including deleting a rule/rules should activate save buttons for user to decide whether to save changes or not.

### Actual Behavior
"Save settings" button stays grayed out after user deletes a rule if user has previously made and saved changes.

### Steps to Reproduce
1. Delete a rule, hit "save";
2. Delete another rule, "save" button stay gray out with a check mark.

### Instance Information
![Screen Shot 2020-02-19 at 9 00 24 AM](https://user-images.githubusercontent.com/49968203/74850228-f12e5780-52f6-11ea-8f52-16edb6dc6e4b.png)

![Screen Shot 2020-02-19 at 9 02 07 AM](https://user-images.githubusercontent.com/49968203/74850237-f390b180-52f6-11ea-8444-17008d735ab2.png)

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by RDmitchell** [comment] 2020-03-27 20:11
instance: dev1
SHA: 9f8ec3a
Org: LBNL 200

When I delete a rule, the Save Changes button remains grayed out. Seems like each time I made a change I should have the option to change it. 

This does not appear to be fixed so I am reopening this and putting it into In Progress

Here are my steps:
* Go to Tax Lot Tab
* Click "Restore Default Rules", which puts up the 2 default rules, the Save Changes button is grayed out
![image](https://user-images.githubusercontent.com/6314950/77796086-e53b6100-702b-11ea-879a-825e2a320161.png)
* I delete the first rule, Address Line 1, and would like to save that change but the "Save Changes" button is still grayed out so I can save the change
![image](https://user-images.githubusercontent.com/6314950/77796294-3ea39000-702c-11ea-9b5d-decc1d678e8e.png)
* I then delete the last rule, and the Save Changes button is still grayed out. I thought when I tested this before, after I deleted the 2nd rule, the Save Changes button was active, but I am not seeing this now.

**Comment by RDmitchell** [comment] 2020-03-27 20:22
@lainsworth8801 -- also, on the Tax Lot tab, if I click the Restore the Defaults button, the Save Changes field is still grayed out. So I can't save that change either

**Comment by RDmitchell** [comment] 2020-03-27 20:25
And if I uncheck the boxes, so that the rules are there but not active, the Save Changes button is still grayed out. 

If I go to the Properties tab and then back to the Tax Lot tab, my changes were not saved, and the rules remain checked.

**Comment by RDmitchell** [comment] 2020-03-27 20:27
And then, for some reason, when I delete all the rules (after having unchecked them so the rules themselves were grayed out), NOW I can save those changes ...
![image](https://user-images.githubusercontent.com/6314950/77797658-af4bac00-702e-11ea-97e7-1ee71b1ba47d.png)

**Comment by RDmitchell** [comment] 2020-03-30 19:24
instance: dev1
SHA: 64cc2d22

In general this now seems to work (maybe the code was updated on dev1 since I last tested). 

There is still a circumstance where I can't save, but I'm not sure I can figure out the exact steps to reproduce it. 

@nllong -- Can this issue be moved to a new project for the next round of work?

**Comment by RDmitchell** [comment] 2020-05-13 05:04
Instance: dev1
SHA: 

This seems to be working on the Property tab, but not on the Tax Lot Tab.

On the Tax Lot tab, I have 2 rules, both of which are unchecked. 
![image](https://user-images.githubusercontent.com/6314950/81772912-e91c2900-949b-11ea-8a85-3fc378254b90.png)

When I check one, to "activate" it, the Save Changes button stays gray
![image](https://user-images.githubusercontent.com/6314950/81773008-34ced280-949c-11ea-92b3-bd02dc5a3bd5.png)

When I make a new rule, the Save Changes button stays gray
![image](https://user-images.githubusercontent.com/6314950/81773096-719ac980-949c-11ea-8f31-b1ee3d44fc2a.png)

**Comment by RDmitchell** [comment] 2020-05-13 05:04
@aviveiros11 / @nllong -- I am moving this back to in progress because it doesn't seem completely fixed.

**Comment by lainsworth8801** [comment] 2020-05-13 12:34
Thanks @RDmitchell

**Comment by RDmitchell** [comment] 2020-07-22 00:57
Instance: dev1
SHA: fd75dea4
Org: LBNL Test 200

When I delete a rule in the Tax Lot tab or the Property tab, the Save Changes button is available to save the changes.

**Closed by RDmitchell** 2020-07-22 00:57 UTC
Labels: 1 Point, Data Quality Checking, Impact-2, P-1
