### ISSUE TITLE
Frontend uses API v3 - Data Quality

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2308] opened 2020-07-20 17:57 UTC
For each v3 endpoint listed below,
- [ ] check for recent changes in the <= v2.1 version and update v3 endpoint if necessary.
- [ ] use it to replace the <= v2.1 version within tests.
- [ ] use it to replace the <= v2.1 version on the frontend. This may be as straightforward as replacing "v2" with "v3" in the `[resource]_service.js`, or it can be as involved as refactoring the frontend code receiving the response.

Once that's complete, 
- [ ] verify that the relevant pages still work as expected - these being the pages where the updated endpoints are used.
- [ ] update this issue with items to test from the user perspective

### Endpoints 
NOTE: Each is listed with the change made in order to create the v3 version.

- **/api/v2/data_quality_checks/ - post**: - investigate - maybe nested rules under data_quality_checks
- **/api/v2/data_quality_checks/{id}/csv/ - get**: - investigate - id is "importfile or cache key"
- **/api/v2/data_quality_checks/data_quality_rules/ - get**: - investigate - maybe nested checks and rules under data_quality
- **/api/v2/data_quality_checks/reset_all_data_quality_rules/ - put**: - deprecate - remove from the frontend
- **/api/v2/data_quality_checks/reset_default_data_quality_rules/ - put**: - move to reset vs (reset_default_...
- **/api/v2/data_quality_checks/results/ - get**: - move to post - investigate moving /progress
- **/api/v2/data_quality_checks/save_data_quality_rules/ - post**: - after nesting, data_quality_checks/id/rules

### Manual Testing
**IMPORTANT: As a non-superuser**, do the following:
- Monkey Test CRUD functionality works on DQ admin page. Attempt to save misconfigured rules as well - Valid severity without a label AND Must /Not Contain with no text.
- run DQ checks on the inventory list page
- run DQ checks on the import mapping page

**Comment by adrian-lara** [comment] 2020-09-24 00:19
@RDmitchell I'm leaving this open for you to test since there were some heavy changes that went into the PR that resolved this ticket. 

Note, I'm also placing it at the top of the project Test list in case you see anything you'd like to change before the release.

**Comment by RDmitchell** [comment] 2020-09-30 20:50
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

Setting up these rules resulted in a 500 error on save
![image](https://user-images.githubusercontent.com/6314950/94738124-d3f94700-0323-11eb-8e25-dec3b0e0ecad.png)

Clicking Save a 2nd time resulted in 404 errors
![image](https://user-images.githubusercontent.com/6314950/94738155-de1b4580-0323-11eb-950a-b1fe970e3cc5.png)

**Comment by adrian-lara** [comment] 2020-10-07 23:18
I wasn't able to reproduce these. If you are able to hit these errors again, let me know any steps you took beforehand (as best you can of course) as well as the organization whose rules you were changing.

**Comment by RDmitchell** [comment] 2020-10-24 02:08
Tested 
* Severity = Valid without a label
program does not allow it
![image](https://user-images.githubusercontent.com/6314950/97065537-e8b3ae00-1562-11eb-83a3-0c4f24422b37.png)

* Must /Not Contain with no text
program does not allow it
![image](https://user-images.githubusercontent.com/6314950/97065553-0b45c700-1563-11eb-9f83-e642573516ff.png)

**Comment by RDmitchell** [comment] 2020-10-24 02:10
Also, can't reproduce the issue that was resulting in a 500/404 error
It saves now without issue
![image](https://user-images.githubusercontent.com/6314950/97065591-519b2600-1563-11eb-88c8-4a8e8c1d3b69.png)

Instance; dev1
SHA: f5bc9220a

**Comment by RDmitchell** [comment] 2020-10-24 02:39
@adrian-lara -- It doesn't seem like DQ results determined on file import are working in terms of adding the labels to the problem records. However they do appear to be working when run from the Inventory List
*****

Here was the result from my import for DQ results in the Mapping Review screen
![image](https://user-images.githubusercontent.com/6314950/97065984-3251c800-1566-11eb-8ba4-55eb38848b25.png)

I saved the mapping then went to inventory, and there do not appear to be any labels applied to the problem records
![image](https://user-images.githubusercontent.com/6314950/97066025-8f4d7e00-1566-11eb-9bb4-2fad3eef856f.png)

Custom ID 101 should have 3 labels, but has none
![image](https://user-images.githubusercontent.com/6314950/97066052-bf951c80-1566-11eb-8954-328180948afd.png)

If I then run the DQ check from the Inventory, I get the same results as when I was importing the file
![image](https://user-images.githubusercontent.com/6314950/97066068-f66b3280-1566-11eb-86e2-61f11067c6f6.png)

And then the labels appear in the Filter by Label box
![image](https://user-images.githubusercontent.com/6314950/97066084-1995e200-1567-11eb-8b6b-d496cda8dd42.png)

And the records actually have the labels applied
![image](https://user-images.githubusercontent.com/6314950/97066092-38947400-1567-11eb-9db2-1941935cff69.png)

*****
Instance: dev1
SHA: 5bc9220a

**Comment by adrian-lara** [comment] 2020-10-24 13:37
@RDmitchell This actually has been the case for a while - that DQ checks on import don't apply labels, but DQ checks on the inventory list page do apply labels.

The issue with the DQ checks during import is that the records are still being "verified" by users. Recall that DQ checks happen on the page where we confirm mappings. In a sense, those aren't "real" records until we click the "Save Mappings" button.
<img width="1384" alt="Screen Shot 2020-10-24 at 9 26 09 AM" src="https://user-images.githubusercontent.com/30608004/97082916-06245e80-15db-11eb-886a-23043710cbea.png">

I do think it'd be useful, but I'd consider it a "new" feature and probably lean towards opening a new ticket for that.

Outside of that, it looks like you were able to test this, and I wonder if this particular ticket is OK to close now?

**Comment by RDmitchell** [comment] 2020-10-26 22:55
@adrian-lara -- I just tested on production, and you are right, no labels are added during import.

I actually think the way the program is set up now makes sense. 

I just wanted to make sure that users that depend on these labels for Salesforce (etc) didn't have changed function, which they don't. 

Am closing !

**Closed by RDmitchell** 2020-10-26 22:55 UTC
Labels: 3 Points, Feature, P-1
