### ISSUE TITLE
Test new BuildingSync's unique ScenarioName unique

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2684] opened 2021-05-19 16:59 UTC
The example file is here: https://drive.google.com/drive/folders/15p-w0RqQDMFCEl6N26U-xOfx1B2WXBFL 

It may be required to update SEED's BuildingSync import to V2.3 before importing this file.

**Comment by macintoshpie** [comment] 2021-06-01 21:43
Done (duplicate of existing ticket in BSync repo)

**Closed by macintoshpie** 2021-06-01 21:43 UTC
Labels: 2 Points, P-1
