### ISSUE TITLE
Investigate why matching 2 files succeeds but 3 fails

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#175] opened 2015-04-03 17:34 UTC
Step through all the code revs that have been introduced since the production to find out why this problem exists. 

If just matching on address, three files don't match, if add PM Property ID to PM files, then all 3 do match

**Comment by StephenCzarnecki** [comment] 2015-04-07 01:48
It is a bit hard to do this because there are commits in develop that have
errors that are not fixed until after a series of other commits.  Here is
what I currently know.  If I go back to 3594d74 (Merge pull request #160
from SEED-platform/issue_65_use_last_imported) then things work.  They stop
working by b507f26 (Merge pull request #163 from
SEED-platform/streetaddress_fix
).  If I apply all of the "address normalization" changes I can see
(checkout 9068a38 and then manually merge with just the streedaddress fixes
in b507f26) but nothing else then it still seems to pass Claudine's test.
Since I think I have the issues with the address normalization changes
straightened out I will try to work through the rest of the commits.

**Comment by RDmitchell** [comment] 2015-04-07 02:44
Thanks Stephen for working through this. It seems like a pretty thankless task. 

And I think it points out a need to do things differently in terms of how we process pull requests. Maybe we really can only do them one at a time, with full integration testing each time, before moving on to the next pull request. We should talk about this.

**Comment by StephenCzarnecki** [comment] 2015-04-07 21:15
Thought I should post an update in case anyone has any ideas.  As best I
can tell the problem seems to come in on 41fe8a8 https://github
.com/SEED-platform/seed/commit/41fe8a8a3c5e6f58cf71efece11446081fc62c6e but
does not involve Spencer's changes to the address parsing or my changes to
the record merging.

All of Spencer's changes are to tasks.py and it seems that noone else has
made any changes to that file so I use the last version of that file that
did not have the streetaddress changes.  The revision before 41fe8a8
(9068a38) passed Claudine's tests with those changes.  Then I went to
41fe8a8 and used both the no-street-address tasks.py and a much later
version of tasks.py that did have the street addess fix (but nothing else
aside from street address changes) and both fail.  Finally I removed all of
the snapshot merging changes I did that were present (in seed/models.py,
seed/tasks.py, and seed/views/main.py) and that still failed the test.

I've been trying to remove some of the other code to go backwards but it is
mostly html and js so I am not sure they have anything to do with the issue
since Claudine's tests are just using the api.  Maybe instead I will start
at 9068a38 and go forward.  There seem to be other changes that I can't
immediately account for (like the change in suggested header names) but I
imagine they are database driven?

**Comment by spencerdutton** [comment] 2015-04-07 21:21
Steven are you able to jump back far enough that you can find a time when
it does pass? Claudine mentioned in the meeting she had a version that
passed at one point I think. Have we checked that this isn't the behaviour
we have always had running Claudine's test API script.

On Tue, Apr 7, 2015 at 2:15 PM, StephenCzarnecki <notifications@github.com>
wrote:

> Thought I should post an update in case anyone has any ideas. As best I
> can tell the problem seems to come in on 41fe8a8 https://github
> .com/SEED-platform/seed/commit/41fe8a8a3c5e6f58cf71efece11446081fc62c6e but
> does not involve Spencer's changes to the address parsing or my changes to
> the record merging.
>
> All of Spencer's changes are to tasks.py and it seems that noone else has
> made any changes to that file so I use the last version of that file that
> did not have the streetaddress changes. The revision before 41fe8a8
> (9068a38) passed Claudine's tests with those changes. Then I went to
> 41fe8a8 and used both the no-street-address tasks.py and a much later
> version of tasks.py that did have the street addess fix (but nothing else
> aside from street address changes) and both fail. Finally I removed all of
> the snapshot merging changes I did that were present (in seed/models.py,
> seed/tasks.py, and seed/views/main.py) and that still failed the test.
>
> I've been trying to remove some of the other code to go backwards but it is
> mostly html and js so I am not sure they have anything to do with the issue
> since Claudine's tests are just using the api. Maybe instead I will start
> at 9068a38 and go forward. There seem to be other changes that I can't
> immediately account for (like the change in suggested header names) but I
> imagine they are database driven?
>
> On Mon, Apr 6, 2015 at 7:44 PM, RDmitchell <notifications@github.com>
> wrote:
>
> > Thanks Stephen for working through this. It seems like a pretty thankless
> > task.
> >
> > And I think it points out a need to do things differently in terms of how
> > we process pull requests. Maybe we really can only do them one at a time,
> > with full integration testing each time, before moving on to the next
> pull
> > request. We should talk about this.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/175#issuecomment-90322970
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/175#issuecomment-90735099>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by StephenCzarnecki** [comment] 2015-04-07 21:53
Yes, 3594d74 (https://github.com/SEED-platform/seed/commit/3594d743b9b9b29f7edf5462a66ea1a8e49a445c)
passes the test.  There are issues with your street address code but if I
use the tasks.py file from 3594d74 in 9068a38 that also passes.  But as
best I can tell 41fe8a8 fails and fails even if I patch it so it does not
have either any of your address changes or any of my snapshot merge changes.

**Comment by RDmitchell** [comment] 2015-04-10 01:01
On Thu, Apr 9, 2015 at 10:24 AM Claudine reported:
When I was testing dang-171 branch, it looks like the matching bug was fixed. Can you confirm this? Maybe we can merge this branch to develop. 

On Thu 4/9/2015 2:17 PM, Stephen reported:
Seems to pass Claudine's test to me.  Did it by hand a couple times too and tried it with 4 files and that seems to all work.

So I am assigning this to Claudine for retesting next Tuesday once the pull request for 171 has been merged next Monday.

**Comment by cycustodio** [comment] 2015-04-14 22:27
Confirmed fixed in seedtest both in GUI and in API script.

**Closed** 2015-04-14 23:45 UTC
Labels: 1, Matching, Ready for Production
