### ISSUE TITLE
Unable to filter inventory by derived columns

### ISSUE THREAD

**Issue by ebeers-png** [SEED-platform/seed#3430] opened 2022-07-26 18:49 UTC
**Describe the bug**

I'm unable to filter the inventory by a derived column on the new/beta inventory list. It seems to work fine on the old inventory list.

**Actual Behavior**

After typing in a filter, the spinner wheel appears, and I see an error for this POST request (where "Source EUI Recalculated" is the name of the derived column):

`https://seeddemostaging.lbl.gov/api/v3/properties/filter/?Source EUI Recalculated__icontains=1&cycle=404&include_related=true&organization_id=303&page=1&per_page=100`

**Steps to Reproduce**

1. Add a derived column to a column profile.
2. Type anything into that column's filter box.

**Instance Information**

I found this error on one of ClearlyEnergy's instances of BEAM, which I'm currently updating to v2.15.1, but I confirmed that the bug was also in SEED on seeddemostaging.lbl.gov.

**Additional Context**

My error log from running BEAM locally (where the name of the column is "Derived column"):
```
File ".../seed/views/v3/properties.py", line 532, in filter
  return get_filtered_results(request, 'property', profile_id=profile_id)
File ".../seed/utils/inventory_filter.py", line 110, in get_filtered_results
  views_list = views_list.annotate(**annotations).filter(filters).order_by(*order_by)
...
File ".../.pyenv/versions/seed/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1339, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: Derived column
```

**Comment by anchapin** [comment] 2022-10-06 13:41
Issue #3438 should fix this issue as well. Therefore, refer to the progress of that issue.

**Comment by anchapin** [comment] 2023-03-23 19:12
I'm going to close this ticket since it is effectively a duplicate of #3438.

**Closed by anchapin** 2023-03-23 19:12 UTC
Labels: Filtering, Bug, BPS, Requires comms after completion, User Support
