### ISSUE TITLE
allow for user to manage column mappings

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1200] opened 2017-01-11 15:31 UTC
Need the ability to:

- view the existing column mappings for an organization
- delete single column mappings for an organization
- delete all column mappings for an organization
- view all columns for an organization
- change display name of column
- change unit of column

This should probably be done as the same time as display names #1191 

Not done in this issue -- move to new issue if desired.
- export/import column mappings from file (?)
- keep track of column mappings by import file so when user returns to 'data mapping' screen they can see the mapped columns and not the suggested column mappings.

**Comment by RDmitchell** [comment] 2018-06-06 01:32
@nllong -- this functionality is all still needed. 

I would say a priority should go to "Save States of Column Mappings" in a similar manner to the new feature to be able to save List Setting states to user defined names. (Based on feedback from users).

Should I make a separate issue for this, as it might be one of the things in this issue that we would do before some of the others ?

**Comment by RDmitchell** [comment] 2018-09-20 19:02
is this on dev1 for testing?

**Comment by nllong** [comment] 2018-09-20 19:02
Yes

**Comment by RDmitchell** [comment] 2018-09-26 23:42
@nllong -- if multiple different types of files are imported, ie, audit data, building lists, espm data, all the field mappings from all the files are shown in the Column, right? 

Also, I am looking at the two column management screens for existing org / existing data. The screen shot below shows a few interesting cases.
* "Beds" was clearly mis-mapped to "BLDGS" so that would be a good candidate for deletion, correct? This would control future mappings, but does nothing to the existing data which was wrongly mapped. Right?
* Two different instances of "city", one capitalized, the other not, both mapped to the internal field "city" and to the Display Name "City" (capitalized). Do I need to keep both those mappings, in order to cover both the "case" situations for future files ? 
![image](https://user-images.githubusercontent.com/6314950/46115265-0c04a700-c1ab-11e8-8d47-94067bce698b.png)

**Comment by RDmitchell** [comment] 2018-09-26 23:45
Another case of two slight variants on the same field in the original data file, both mapped to the same internal field and Display name. 

So I need to keep both those mappings to cover both the possibilities in an imported data file, right? 
![image](https://user-images.githubusercontent.com/6314950/46115388-8b927600-c1ab-11e8-8188-65787f26b09a.png)

**Comment by RDmitchell** [comment] 2018-09-26 23:51
@nllong  -- One suggestion for future improvements -- being able to sort by any of the columns. Should I make a separate issue for this? 

I am thinking, looking at this particular example, that it might be nice to sort by the internal field name or the Display name, so that I could see all the different variants in the original data files that get mapped to jurisdiction_tax_lot_ID. It might make it easier to do some spot checking of mappings.
![image](https://user-images.githubusercontent.com/6314950/46115543-4c185980-c1ac-11e8-91b8-3c8cf148c0d3.png)

**Comment by RDmitchell** [comment] 2018-09-26 23:55
@nllong --

Looking at the mapping for a specific file (in Data), I can see here is where I made the wrong mapping between "Beds" and "BLDGS".

So for now, to fix this, I would need to reimport the file (or maybe all the records but just a few fields, ie, the matching field and the "Beds" field) in order to get the data properly mapped.

Right? 
![image](https://user-images.githubusercontent.com/6314950/46115690-ed9fab00-c1ac-11e8-8f57-23a2aba322c7.png)

**Comment by RDmitchell** [comment] 2018-09-26 23:59
Another case of bad mapping which becomes apparent in this screen. 

Then the issue is what to do about it, but I know that's for another time to deal with.

![image](https://user-images.githubusercontent.com/6314950/46115791-7b7b9600-c1ad-11e8-86ee-ba5b5d766f8b.png)

**Comment by RDmitchell** [comment] 2018-09-27 00:45
Updating field names in Column Settings seems to work nicely.
BLDGS field is in a couple different cycles (Tax Lot tab): 
* Another set of tests
* Berkeley Building List Test

I changed the name to BLDGS 22 in Column Settings, and it is changed in the data in both cycles.

**Comment by RDmitchell** [comment] 2018-09-27 00:59
Protected fields in Column Settings also works well
![image](https://user-images.githubusercontent.com/6314950/46117399-e8932980-c1b5-11e8-85c2-ff476ac822ee.png)

Need to do a bit more testing plus check with SF to make sure we are covering their use case.

**Comment by RDmitchell** [comment] 2018-10-01 23:52
QUESTION:
If you delete all mappings in Column Mappings, should the list of Column Settings be empty in Column Settings? 

I guess not, because 

* Column Settings represents columns that are already mapped.
* Column Mappings represents how columns will be mapped in the future when new files are imported and mapped?

**Comment by RDmitchell** [comment] 2018-10-02 02:01
Here is a link to the gdrive issue folder with a doc about some of my testing, etc. 
https://drive.google.com/drive/folders/1EzR81XzD9BczUPalfsLQhsB-eZVe2XNv?usp=sharing

@nllong -- I think I am ready to close this issue, but would like to discuss some of my questions with you if you have time in the next day or two.

**Comment by RDmitchell** [comment] 2018-10-02 19:43
I am answering my own question about why some information is shown in Column Settings vs Column Mappings
![image](https://user-images.githubusercontent.com/6314950/46372698-be6fba80-c640-11e8-8d59-0cc3f275026b.png)

**Comment by RDmitchell** [comment] 2018-10-02 19:48
This is a good start, and there are more things to add to this functionality, but the current functionality hopefully addresses at least San Francisco's issues with mappings. I may add some more issues for future work as I think about them, and/or hear back from SF. But I am going to close this issue.

**Closed by RDmitchell** 2018-10-02 19:48 UTC
Labels: 2018 Sept Release, 5 Points, Impact-2, Mapping, P-2
