### ISSUE TITLE
Add javascript tests to Travis-CI

### ISSUE THREAD

**Issue by pipermerriam** [SEED-platform/seed#625] opened 2015-12-22 17:48 UTC
The javascript test suite should probably be added to travis ci.  Otherwise it's likely to just have random failures that go unfixed.

**Comment by RDmitchell** [comment] 2015-12-22 18:07
Who is a likely candidate to do that work?

**Comment by pipermerriam** [comment] 2015-12-22 18:14
@danielmcquillen or myself are the two that come to mind.  They basically just need to be adjusted such that they can be run from the command line.  There's already a handful of tools for doing this so we just need to pick one and get it wired up.

**Comment by axelstudios** [comment] 2017-06-07 17:45
No longer an issue - duplicate of #443

**Closed by axelstudios** 2017-06-07 17:45 UTC
