### ISSUE TITLE
Building Detail only shows fields that contain data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#67] opened 2014-11-20 05:30 UTC
In the Building Detail, the program only displays the fields that have data in them. If the fields are blank they are not shown in this view (although they are shown in the Building List view). This might be a good feature, but one problem with it is that the user doesn't know which fields do not have data, and does not have the opportunity to edit those blank fields "by hand" which is an option in this view.

This needs some design thought.

**Comment by RDmitchell** [comment] 2015-07-20 19:59
I will add a simple set of example data and a detailed description of the issue later today.

**Comment by RDmitchell** [comment] 2015-07-21 00:38
Here is the link to the folder with the more detailed description and a set of data which shows the problem.

In thinking about this, it could be that this might lead us to a more fundamental issue about how data is put into a building snapshot when it is imported, ie, if the data is blank, does the field still get data written into the associated "Source" field at the top of the Building Snapshot table, which links the data back to the import source. 

So this might be a bigger issue than we think. If you can figure out what is happening, we might want to have a design discussion with a larger set of people before you imlement any changes. 

Robin

**Comment by nicholasserra** [comment] 2015-07-22 17:24
So I think this is kinda the same issue as #247, but with the DB fields. It looks like blank fields are simply being skipped, instead of being set to empty string. The FE then filters out those null fields.

**Comment by RDmitchell** [comment] 2015-07-22 17:30
Yes, I was thinking that might be the case. We need to change it so that the blank fields are written to the database, just with null values. Like you did with the fields with blank data going into the JSON blob. Is this something you can take on?

**Comment by nicholasserra** [comment] 2015-07-22 17:44
Currently investigating whether my fix in the other PR will also handle this.

**Comment by nicholasserra** [comment] 2015-07-22 18:18
Looks like my previous fix won't handle this. Trying to figure out if the issue is on the csv parse itself. Trying to hunt down exactly where that even happens is a task in itself though, it seems.

**Comment by RDmitchell** [comment] 2015-07-22 18:33
Yes it will be a bit of work to figure out how all this works, but we need to understand it for many reasons. When you figure it all out, it would be great if you document the way that the program parses the CSV and puts data in the blob or the building snapshot table fields (or not as in this case). 

I believe that Miles has discovered some of how this all works, and maybe he can chime in on this issue.

**Comment by nicholasserra** [comment] 2015-07-22 18:36
Will do

cc @mmclark

**Comment by mmclark** [comment] 2015-07-22 22:33
The initial parsing is done in seed/tasks.py, starting in the function _save_raw_data().  You'll notice there's an MCM parser object that's created (the exact type of which depends on the file type).  Check out mcm/reader.py and mcm/cleaners.py.

**Comment by nicholasserra** [comment] 2015-07-23 03:53
Yup, so looks like the magic for this fix is in those cleaners.

**Comment by nicholasserra** [comment] 2015-07-23 19:23
@RDmitchell 

So I had a fix in mind that work would for varchar field, in which we could save them as blank instead of null, and show them on the FE. But that will not work for other field types, like the FloatField on `gross_floor_area`, because you can't save it as empty string. 

The only real fix I can think of for this situation is to show all of the null fields on the detail view, and allow you to edit any of them. But that would also show fields that weren't present in the original file. Aka if your csv does not have `gross_floor_area`, you could still edit `gross_floor_area` once it's imported.

If we go that route, it may be best to section those fields off somehow. Definitely needs some design thought though.

**Comment by RDmitchell** [comment] 2015-07-23 19:48
Hmmm. I would prefer that we NOT show the fields that are in the Building snapshot table but not in the original imported data.

**Comment by nicholasserra** [comment] 2015-07-23 21:12
Gotcha. There may be a way for the FE to do that logic.

**Comment by RDmitchell** [comment] 2015-08-11 23:57
Reading back through this thread, I think it is fine that blank fields are being skipped and set to null -- I don't think we would actually want them to be set to an empty string. 

I think all that is required here is a change to the FE to not filter on those null fields. We don't need that automatic filter now that we have a way for user to filter for null data in fields, ie, "".

So can you make that FE change to show all the fields even if they have null data? Or should I assign this to someone else?

**Comment by nicholasserra** [comment] 2015-08-12 18:01
Up to you, if someone else has better knowledge of the FE codebase then they might be better suited. If not, I can take it on :)

**Comment by nicholasserra** [comment] 2015-08-19 17:50
So to confirm, show all fields on the building detail page, even if they are blank/null?

**Comment by RDmitchell** [comment] 2015-08-19 18:03
Yes please !

Here is an example.
Below is the Building List. You can see that for the "True Lane" address, the Year Built field (a field in the Building Snapshot table) is blank
![image](https://cloud.githubusercontent.com/assets/6314950/9364472/64f59612-4661-11e5-8a00-39fc924ea8ec.png)

Looking at the detail view for the building with blank data for that field, Year Built does not appear. It would be good for it to appear, without data, so that the user could edit the master record and fill in a value, if they want to.
![image](https://cloud.githubusercontent.com/assets/6314950/9364528/9e846ef8-4661-11e5-9fc8-325d5bfcf50f.png)

For the 2nd record, which does have data in the Year Built field, that field is displayed in the detail view
![image](https://cloud.githubusercontent.com/assets/6314950/9364553/da941d9e-4661-11e5-94af-051d4f26bb8f.png)

**Comment by nicholasserra** [comment] 2015-08-19 18:05
Ok. This will end up showing a ton of blank fields though. I'll get a screenshot in here when I implement it.

**Comment by RDmitchell** [comment] 2015-08-19 18:06
Yes, do a screen shot to show what this will end up looking like. Thanks !

**Comment by RDmitchell** [comment] 2015-08-19 20:02
Maybe if it is ridiculous in terms of the blank fields, ie, the 256 fields from PM that are mostly blank, we could have a checkbox at the top of the screen giving the user the choice to see fields with blank values (if checked) or not (if unchecked). So they could see all the blanks, edit them if desired, and then turn off the display of blank fields

**Comment by nicholasserra** [comment] 2015-08-19 20:17
Looks like the db has about 50 fields. My screen isn't big enough to show everything in one screenshot, but it's not too bad. 

Before
![screen shot 2015-08-19 at 4 13 37 pm](https://cloud.githubusercontent.com/assets/512288/9367809/c1927ab2-468d-11e5-8eaf-30987fda1c52.png)

After
![screen shot 2015-08-19 at 4 16 59 pm](https://cloud.githubusercontent.com/assets/512288/9367818/c6af56d2-468d-11e5-967b-47601dee3171.png)

**Comment by nicholasserra** [comment] 2015-08-19 20:18
I'm trying to see if there's a simple way to make the main view show populated fields and the edit view show all fields.

**Comment by RDmitchell** [comment] 2015-08-19 20:29
There are 41 data fields in the Building snapshot table not including the extra_data and extra_data_sources fields.

I think the users will still want to see the empty fields in the non-edit view, what you are calling the main view. They won't want to have to go into the Edit view to see if there are blanks. 

I think displaying all 41 fields in the main view is fine. Just do that for now.

Thanks !

Robin

**Comment by nicholasserra** [comment] 2015-08-25 16:19
Assigning to @RDmitchell for testing.

**Comment by RDmitchell** [comment] 2015-08-25 16:27
Claudine -- can you test this, after you have done the testing for the August release. I have assigned it to you. Thx

**Comment by RDmitchell** [comment] 2015-08-25 19:44
I have tested this and it is working. There may be refinements later, but I am closing this issue.

**Comment by RDmitchell** [comment] 2015-11-19 18:07
This is working - program shows all the fields -- not sure this is the best final solution but it is much better than it was and can be refined over time. Am closing

**Closed** 2016-02-05 01:21 UTC
Labels: 2, Building Detail, Design Issue
