### ISSUE TITLE
filter is recognizing the "N" in Null

### ISSUE THREAD

**Issue by BenchmarkDC** [SEED-platform/seed#3766] opened 2023-01-19 21:46 UTC
This might have been resolved in previous versions but I noticed that in at least 2.15 when I try and filter a column that contains the letter "N" it is returning all the Null values as well.

**Comment by RDmitchell** [comment] 2023-01-19 21:58
@BenchmarkDC -- what exactly are you filtering on? 

In 2.15, when I filter on "N", I am not getting the records with null values for that field. 

Here is the test I did

In this Inventory list, for Address Line 1, there are records with no value in that field
![image](https://user-images.githubusercontent.com/6314950/213570966-86717aec-6e18-4406-b7b0-a20cc01e1e7c.png)

If I filter on N, I get the following records, and none that have that field set to Null
![image](https://user-images.githubusercontent.com/6314950/213570998-e0971421-f494-4b2d-abc2-1e47e5417012.png)

I suspect you are filtering in some other way? 

Instance: LBNL Production
Version: 2.15.1
SHA: 09736c1d6

**Comment by RDmitchell** [comment] 2023-03-21 03:12
I am going to test this on the latest version of SEED.

**Comment by RDmitchell** [comment] 2023-04-07 20:42
@BenchmarkDC -- I can't reproduce this problem, so I am closing this ticket. If you can give an example, with screenshots, of this issue, we can reopen the issue.

**Closed by RDmitchell** 2023-04-07 20:42 UTC
Labels: Bug
